title: Kyoungsu Kim
pitch: "Helloooooo world"
cc: 
description: >- # this means to ignore newlines until "baseurl:"
  This is Geun Young's blog site. I like drawing, code art and robots. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  KyoungSuKim
facebook_username: 
email: Kyoungsukim64@gmail.com
author_website: https://gopigo.com
repo: https://github.com/KyoungSuKim/site-test.git
# Build settings
markdown: kramdown
theme: academic
plugins:
  - jekyll-feed




# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
